#!/usr/bin/env bash

### Options ###
screen="Tout l'écran"
area="Une zone de l'écran"
window="Fenètre active"

# Variable passed to rofi
options="$screen\n$area\n$window"

chosen="$(echo -e "$options" | rofi -p "Capture d'écran"  -dmenu -no-show-icons -i -selected-row 0 -lines 3 -m -4 -width 350)"

sleep 0.2
case $chosen in
    $screen)
        scrot -e 'mv $f ~/Desktop/;feh ~/Desktop/$n' -p
        ;;
    $area)
        scrot -e 'mv $f ~/Desktop/;feh ~/Desktop/$n' -s
        ;;
    $window)
        scrot -e 'mv $f ~/Desktop/;feh ~/Desktop/$n' -p -u
        ;;
esac


