---
- name: Install bat package
  apt:
    name: bat
    state: present
    dpkg_options: "force-overwrite"  # Issue specific with bat and ripgrep https://github.com/sharkdp/bat/issues/938#issuecomment-646745610
  become: true
