---
- name: Install bat package
  apt:
    name: bat
    state: present
    dpkg_options: "force-overwrite" # Issue specific with bat and ripgrep https://github.com/sharkdp/bat/issues/938#issuecomment-646745610
  become: yes


- name: Get batcat path
  shell: which batcat
  register: batcat_path
  changed_when: false
  ignore_errors: true

- name: Add alias for batcat
  blockinfile:
    path: ~/.zshrc_post
    marker: "# {mark} ANSIBLE MANAGED bat BLOCK -->"
    block: |
      alias bat="{{ batcat_path.stdout }}"
    create: true
  when: batcat_path is succeeded
