---
- name: Install bat package
  ansible.builtin.apt:
    name: bat
    state: present
    dpkg_options: "force-overwrite"  # Issue specific with bat and ripgrep https://github.com/sharkdp/bat/issues/938#issuecomment-646745610
  become: true

- name: Get batcat path
  ansible.builtin.command: which batcat
  register: shell_batcat_path
  changed_when: false
  ignore_errors: true

- name: Add alias for batcat
  ansible.builtin.blockinfile:
    path: ~/.zshrc_post
    marker: "# {mark} ANSIBLE MANAGED bat BLOCK -->"
    block: |
      alias bat="{{ shell_batcat_path.stdout }}"
    create: true
    mode: 'u=rw,g=r'
  when: shell_batcat_path is succeeded
