---
- name: Install unzip
  ansible.builtin.apt:
    name: unzip
    state: present
  become: true

- name: Unarchive exa binary
  ansible.builtin.unarchive:
    src: https://github.com/ogham/exa/releases/download/v{{ exa_version }}/exa-linux-x86_64-v{{ exa_version }}.zip
    dest: /tmp
    remote_src: true
    creates: /usr/local/bin/exa
  become: true

- name: Rename exa binary
  ansible.builtin.command:
    cmd: mv -f /tmp/bin/exa /usr/local/bin/exa
    creates: /usr/local/bin/exa
  become: true

- name: Rename exa man page
  ansible.builtin.command:
    cmd: mv -f /tmp/man/exa.1 /usr/share/man/man1/exa.1
    creates: /usr/local/bin/exa
  become: true

- name: Fetch zsh-aliases-exa alias for oh-my-zsh aliases
  ansible.builtin.git:
    repo: 'https://github.com/DarrinTisdale/zsh-aliases-exa.git'
    dest: '~/.oh-my-custom/plugins/zsh-aliases-exa'
    version: 'master'
