---
- name: Install fd package
  ansible.builtin.apt:
    name: fd-find
    state: present
  become: true

- name: Get fdfind path
  ansible.builtin.command: which fdfind
  register: shell_fdfind_path
  changed_when: false
  ignore_errors: true

- name: Add symlink to fdfind
  ansible.builtin.file:
    src: "{{ shell_fdfind_path.stdout }}"
    dest: /usr/bin/fd
    owner: root
    group: root
    state: link
  become: true
  when: shell_fdfind_path is succeeded and shell_fdfind_path.stdout != "/usr/bin/fd"
