---
- name: Install fd package
  apt:
    name: fd-find
    state: present
  become: true

- name: Get fdfind path
  command: which fdfind
  register: fdfind_path
  changed_when: false
  ignore_errors: true

- name: Add symlink to fdfind
  ansible.builtin.file:
    src: "{{ fdfind_path.stdout }}"
    dest: /usr/bin/fd
    owner: root
    group: root
    state: link
  become: true
  when: fdfind_path is succeeded and fdfind_path.stdout != "/usr/bin/fd"
