---
- name: Retrieve Powerline fonts
  git:
    dest: '/tmp/powerline-fonts'
    repo: 'https://github.com/powerline/fonts.git'
    depth: 1

- name: Install Powerline fonts
  command:
    chdir: '/tmp/powerline-fonts'
    cmd: './install.sh'

- name: Clean artifact path
  file:
    state: absent
    path: '/tmp/powerline-fonts'


