---
- name: Unarchive fx binary
  get_url:
      url: 'https://github.com/antonmedv/fx/releases/download/{{ fx_version }}/fx_linux_amd64'
      dest: /usr/local/bin
      mode: "u=rwx,go=rx"
  become: true

- name: Add link to fx binary
  ansible.builtin.file:
    src: /usr/local/bin/fx_linux_amd64
    dest: /usr/local/bin/fx
    state: link
  become: true
