---
- name: "Fail if git user not defined"
  fail:
    msg: "You MUST define a valid git_username and git_email configuration"
  when: (not git_username ) or (not git_email)

- name: Install Git
  apt:
    name: git
    state: present
  become: true

- name: Copy gitignore configuration
  copy:
    src: gitignore
    dest: ~/.gitignore
    mode: 'u=rw'

- name: Apply gitconfig configuration
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig
    mode: 'u=rw'

- name: Install git extras
  apt:
    name: git-extras
    state: present
  become: true
