---
- name: Install glances dependencies
  apt:
    name:
      - python3-pip
      - python3-virtualenv
      - python3-setuptools
      - python3-psutil
    state: present
  become: true

- name: Install glances
  pip:
    name: "glances=={{ glances_version }}"
    # Here to force the usage of sysem pip
    # instead of virtualenv location
    executable: "/usr/bin/pip3"
