---
- name: Install pip dependencies
  apt:
    name:
      - python3-pip
      - python3-virtualenv
      - python3-setuptools
    state: present
  become: true

- name: Install httpie
  # @TODO not working if you run ansible in a pipenv
  # Find a way to force global even in pipenv
  pip:
    name: "httpie=={{ httpie_version }}"
    # Here to force the usage of sysem pip
    # instead of virtualenv location
    executable: "/usr/bin/pip3"
