---
- name: Ensure locale package is available
  apt:
    name: locales
    state: present
  become: true

- name: Ensure locales are available
  locale_gen:
    name: "{{ item }}"
    state: present
  loop: '{{ shell_user_locales
    | dict2items
    | selectattr("value", "search", ".UTF-8")
    | map(attribute="value")
    | list
    | unique + shell_extra_locales }}'
  become: true

- name: Define locales for current user
  template:
    src: locales.j2
    dest: ~/.locales
    mode: 'u=rw,g=r'

- name: Add locales to zshrc config
  blockinfile:
    path: ~/.zshrc_pre
    create: true
    marker: "# {mark} ANSIBLE MANAGED locales BLOCK -->"
    block: |
      if [ -f ~/.locales ]; then
        source ~/.locales
      fi
    mode: 'u=rw,g=r'
