---
- name: "Install locales"
  ansible.builtin.import_tasks: locales.yml
  tags: locales

- name: "Install git"
  ansible.builtin.import_tasks: git.yml
  tags: git

- name: "Install zsh"
  ansible.builtin.import_tasks: zsh.yml
  tags: zsh

- name: "Install tmux"
  ansible.builtin.import_tasks: tmux.yml
  tags: tmux

- name: "Install autojump"
  ansible.builtin.import_tasks: autojump.yml
  tags: autojump

- name: "Install direnv"
  ansible.builtin.import_tasks: direnv.yml
  tags: direnv

- name: "Install fd"
  ansible.builtin.import_tasks: fd.yml
  tags: fd

- name: "Install fzf"
  ansible.builtin.import_tasks: fzf.yml
  tags: fzf

- name: "Install bat"
  ansible.builtin.import_tasks: bat.yml
  tags: bat

- name: "Install eza"
  ansible.builtin.import_tasks: eza.yml
  tags: eza

- name: "Install ripgrep"
  ansible.builtin.import_tasks: ripgrep.yml
  tags: ripgrep

- name: "Install fx"
  ansible.builtin.import_tasks: fx.yml
  tags: fx

- name: "Install jq"
  ansible.builtin.import_tasks: jq.yml
  tags: jq

- name: "Install progress"
  ansible.builtin.import_tasks: progress.yml
  tags: progress
