---
- name: Install fontconfig
  apt:
    name: fontconfig
    state: present
  become: yes

- name: Check Powerline fonts on host
  shell: 'fc-list | grep -i powerline'
  register: fonts
  failed_when: "fonts.rc == 2"
  changed_when: false

- name: Retrieve Powerline fonts
  git:
    dest: '/tmp/powerline-fonts'
    repo: 'https://github.com/powerline/fonts.git'
    version: master
    depth: "1"
  when: (fonts is not defined) or (fonts.stdout | length == 0)

- name: Install Powerline fonts
  command:
    chdir: '/tmp/powerline-fonts'
    cmd: './install.sh'
  when: (fonts is not defined) or (fonts.stdout | length == 0)

- name: Clean artifact path
  file:
    state: absent
    path: '/tmp/powerline-fonts'
  when: (fonts is not defined) or (fonts.stdout | length == 0)
