---
- name: Install Tmux
  apt:
    name:
      - tmux
      - xsel
    state: present
  become: true

- name: Copy Tmux configuration
  copy:
    src: tmux.conf
    dest: '~/.tmux.conf'
    mode: 'u=rw,g=r'
  notify: Refresh tmux configuration

- name: Install Tmux Plugin Manager
  git:
    dest: '~/.tmux/plugins/tpm'
    repo: 'https://github.com/tmux-plugins/tpm.git'
    depth: "1"
    version: 'master'
  notify: Refresh tmux configuration
