---
- name: Install Tmux
  apt:
    name:
      - tmux
      - xsel
    state: present
  become: yes

- name: Copy Tmux configuration
  copy:
    src: tmux.conf
    dest: '~/.tmux.conf'

- name: Install Tmux Plugin Manager
  git:
    dest: '~/.tmux/plugins/tpm'
    repo: 'https://github.com/tmux-plugins/tpm.git'
    depth: 1
  register: "tmux_clone"

- name: Install Tmux fonts
  git:
    dest: '~/.tmux/fonts'
    repo: 'https://github.com/powerline/fonts.git'
    depth: 1

- name: Source Tmux configuration
  shell: 'tmux start-server \; source ~/.tmux.conf' # Only solution to have a running tmux while sourcing configuration
  when: "tmux_clone is changed"

- name: Update TPM configuration
  command:
    chdir: '~'
    cmd: '~/.tmux/plugins/tpm/bin/install_plugins'
  when: "tmux_clone is changed"
