---
- name: Install Tmux
  apt:
    name:
      - tmux
      - xsel
    state: present
  become: yes

- name: Copy Tmux configuration
  copy:
    src: tmux.conf
    dest: '~/.tmux.conf'

- name: Install Tmux Plugin Manager
  git:
    dest: '~/.tmux/plugins/tpm'
    repo: 'https://github.com/tmux-plugins/tpm.git'
    depth: "1"
  register: "tmux_clone"

- name: Install Tmux fonts
  git:
    dest: '~/.tmux/fonts'
    repo: 'https://github.com/powerline/fonts.git'
    depth: "1"

- name: Source Tmux and TPM configurations
  shell: 'tmux new "sleep 0.1 && tmux source ~/.tmux.conf && ~/.tmux/plugins/tpm/bin/install_plugins"'
  register: "tmux_content"
  when: "tmux_clone is changed"
