---
- name: Install Tmux
  apt:
    name:
      - tmux
      - xsel
    state: present
  become: true

- name: Copy Tmux configuration
  copy:
    src: tmux.conf
    dest: '~/.tmux.conf'
    mode: 'u=rw,g=r'

- name: Install Tmux Plugin Manager
  git:
    dest: '~/.tmux/plugins/tpm'
    repo: 'https://github.com/tmux-plugins/tpm.git'
    depth: "1"
    version: 'master'
  register: "tmux_clone"

- name: Source Tmux and TPM configurations (out tmux)
  shell: 'tmux new-session -d -s ansible-tmux-cfg "sleep 0.1 && tmux source-file ~/.tmux.conf && ~/.tmux/plugins/tpm/bin/install_plugins"'
  when: 'lookup("env", "TMUX") == "" and tmux_clone is changed'

- name: Source Tmux and TPM configurations (in tmux)
  shell: 'tmux source ~/.tmux.conf && ~/.tmux/plugins/tpm/bin/install_plugins'
  when: 'lookup("env", "TMUX") != "" and tmux_clone is changed'
