---
- name: Install Zsh
  apt:
    name: zsh
    state: present
  become: true

- name: Set current shell to Zsh
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  register: set_default_shell

- name: "End play if zsh is not the current shell (restart your terminal)"
  ansible.builtin.meta: end_host
  when: set_default_shell.changed

- name: Clone oh-my-zsh for users
  git:
    dest: '~/.oh-my-zsh'
    repo: 'https://github.com/robbyrussell/oh-my-zsh.git'
    update: true
    accept_hostkey: true
    version: "master"

- name: Copy .zshrc for users
  template:
    src: zshrc.j2
    dest: ~/.zshrc
    mode: 'u=rw,g=r'

- name: Import lambda-gister theme
  get_url:
    url: 'https://raw.githubusercontent.com/ergenekonyigit/lambda-gitster/main/lambda-gitster.zsh-theme'
    dest: ~/.oh-my-zsh/themes/lambda-gitster.zsh-theme

- name: Create custom plugin directory
  file:
    path: ~/.oh-my-custom/plugins
    state: directory
    mode: 'u=rwx,g=rx'

- name: Add extra plugins
  git:
    repo: "{{ item.value }}"
    dest: "~/.oh-my-custom/plugins/{{ item.key }}"
    version: 'master'
  loop: "{{ oh_my_sh_extra_plugins | dict2items }}"
