---
- name: Install Zsh
  ansible.builtin.apt:
    name: zsh
    state: present
  become: true

- name: Set current shell to Zsh
  become: true
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    shell: /bin/zsh
  register: shell_set_default_shell

- name: "End play if zsh is not the current shell (restart your terminal)"
  ansible.builtin.meta: end_host
  when: shell_set_default_shell.changed  # noqa: no-handler

- name: Clone oh-my-zsh for users
  ansible.builtin.git:
    dest: '~/.oh-my-zsh'
    repo: 'https://github.com/robbyrussell/oh-my-zsh.git'
    update: true
    accept_hostkey: true
    version: "master"

- name: Copy .zshrc for users
  ansible.builtin.template:
    src: zshrc.j2
    dest: ~/.zshrc
    mode: 'u=rw,g=r'

- name: Import lambda-gister theme
  ansible.builtin.get_url:
    url: 'https://raw.githubusercontent.com/ergenekonyigit/lambda-gitster/main/lambda-gitster.zsh-theme'
    dest: ~/.oh-my-zsh/themes/lambda-gitster.zsh-theme
    mode: 'u=rw,g=r'

- name: Create custom plugin directory
  ansible.builtin.file:
    path: ~/.oh-my-custom/plugins
    state: directory
    mode: 'u=rwx,g=rx'

- name: Add extra plugins
  ansible.builtin.git:
    repo: "{{ item.value }}"
    dest: "~/.oh-my-custom/plugins/{{ item.key }}"
    version: 'master'
  loop: "{{ shell_oh_my_sh_extra_plugins | dict2items }}"

- name: "Add alias to load omz module on the fly"
  ansible.builtin.blockinfile:
    path: ~/.zshrc_post
    marker: "# {mark} ANSIBLE MANAGED omz ^plugin BLOCK -->"
    block: |
      alias omzp="omz plugin load"
    create: true
    mode: 'u=rw,g=r'
