---
- name: Fetch nvm install script
  get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_version }}/install.sh
    dest: /tmp/nvm-installer
    mode: 'u=rwx,g=rx,o=rx'

- name: Launch nvm installer
  shell: bash /tmp/nvm-installer

- name: Add zsh-nvm plugin
  git:
    repo: 'https://github.com/lukechilds/zsh-nvm'
    dest: '~/.oh-my-zsh/custom/plugins/zsh-nvm'

- name: Add zsh-nvm local settings
  blockinfile:
    path: ~/.zshrc_pre_local
    create: true
    marker: "# {mark} ANSIBLE MANAGED NVM BLOCK -->"
    block: |
      export NVM_LAZY_LOAD=true
      export NVM_COMPLETION=true
