---
- hosts: all
  tasks:
  - name: "Limit to Ubuntu distributions"
    import_role:
      name: utils
      tasks_from: filter_distribution

  - name: "Install gnome config"
    include_role:
      name: gnome
    tags: gnome
