---
- hosts: all
  tasks:
  - name: "Limit to Ubuntu distributions"
    import_role:
      name: utils
      tasks_from: filter_distribution

  - name: "Install curl"
    apt:
      name: curl
      state: present
    tags: curl
    become: yes

  - name: "Install neovim"
    import_role:
      name: neovim
    tags: neovim

  - name: "Install git"
    import_role:
      name: git
    tags: git

  - name: "Install htop"
    import_role:
      name: htop
    tags: htop
