---
- hosts: all
  tasks:
  - name: "Limit to Ubuntu distributions"
    import_role:
      name: utils
      tasks_from: filter_distribution

  - name: "Install curl"
    apt:
      name: curl
      state: present
    tags: curl
    become: yes

  - name: "Install locales"
    import_role:
      name: locales
    tags: locales

  - name: "Install neovim"
    import_role:
      name: neovim
    tags: neovim

  - name: "Install git"
    import_role:
      name: git
    tags: git

  - name: "Install zsh"
    import_role:
      name: zsh
    tags: zsh

  - name: "Install Powerline fonts"
    import_role:
      name: powerline_fonts
    tags: powerline_fonts

  - name: "Install tmux"
    import_role:
      name: tmux
    tags: tmux

  - name: "Install autojump"
    import_role:
      name: autojump
    tags: autojump

  - name: "Install fd"
    import_role:
      name: fd
    tags: fd

  - name: "Install fzf"
    import_role:
      name: fzf
    tags: fzf

  - name: "Install bat"
    import_role:
      name: bat
    tags: bat

  - name: "Install exa"
    import_role:
      name: exa
    tags: exa

  - name: "Install ripgrep"
    import_role:
      name: ripgrep
    tags: ripgrep

