---
- hosts: all
  pre_tasks:
    - name: Limit to Ubuntu distributions
      import_role:
        name: utils
        tasks_from: filter_distribution
      tags:
        - always
    - name: Install prerequisites
      import_role:
        name: utils
        tasks_from: module_prerequisites
      tags:
        - always
    - name: Update apt cache
      import_role:
        name: utils
        tasks_from: apt_cache
      tags:
        - always
  roles:
    - role: shell
      tags: shell

    - role: programming
      tags: programming

    - role: tools
      tags: tools

    - role: docker
      tags:
        - docker
        - tools

    - role: kube
      tags:
        - kube
        - tools

    - role: gnome
      tags: gnome

    - role: desktop
      tags: desktop

    - role: extended_desktop
      tags: extended_desktop
