---
- hosts: all
  pre_tasks:
    - name: Limit to Debian like distributions
      fail:
        msg: "{{ ansible_distribution }} is not supported with this tag."
      when: (ansible_distribution != "Ubuntu") and
            (ansible_distribution != "Debian")

- name: "Install tools"
  hosts: all
  roles:
    - role: minimal_tools
      tags: minimal_tools
    - role: shell
      tags: shell
    - role: tools
      tags: tools

- name: "Install gnome config"
  hosts: gnome
  roles:
    - role: gnome
      tags: gnome

- name: "Install desktop tools"
  hosts: desktop
  roles:
    - role: desktop
      tags: desktop
