---
- hosts: all
  pre_tasks:
    - name: Limit to Debian like distributions
      fail:
        msg: "{{ ansible_distribution }} is not supported with this tag."
      when: (ansible_distribution != "Ubuntu") and
            (ansible_distribution != "Debian")

- name: "Install minimal tools"
  hosts: all
  roles:
    - role: minimal_tools
      tags:
        - minimal_tools

- name: "Install shell"
  hosts: shell
  roles:
    - role: shell
      tags:
        - shell

- name: "Install tools"
  hosts: all
  roles:
    - role: tools
      tags:
        - tools
