---
- hosts: all
  gather_facts: yes
  pre_tasks:
    - name: Limit to Debian like distributions
      fail:
        msg: "{{ ansible_distribution }} is not supported with this tag."
      when: (ansible_distribution != "Ubuntu") and
            (ansible_distribution != "Debian")

- name: "Install basic_networking"
  gather_facts: false
  hosts: basic_networking
  roles:
    - role: curl
      tags: curl
    - role: git
      tags: git

- name: "Install shell"
  gather_facts: true
  hosts: shell
  roles:
    - role: zsh
      tags: zsh
