---
- hosts: all
  roles:
    - role: shell
      tags: shell

    - role: programming
      tags: programming

    - role: tools
      tags: tools

    - role: docker
      tags:
        - docker
        - tools

    - role: kube
      tags:
        - kube
        - tools

    - role: gnome
      tags: gnome

    - role: desktop
      tags: desktop
      
    - role: extended_desktop
      tags: extended_desktop
