---
- hosts: all

  pre_tasks:
    - name: Limit to Ubuntu distributions
      import_role:
        name: utils
        tasks_from: filter_distribution
      tags:
        - always

    - name: Update apt cache
      import_role:
        name: utils
        tasks_from: apt_cache
      tags:
        - always

    - name: Install prerequisites
      import_role:
        name: utils
        tasks_from: module_prerequisites
      tags:
        - always

    - name: Get common vars
      import_role:
        name: utils
        tasks_from: common_vars
      tags:
        - always

    - name: Get available desktop environment
      import_role:
        name: utils
        tasks_from: stat_desktop_environment
      tags:
        - always

  roles:
    - role: shell
      tags: shell

    - role: tools
      tags: tools
    - role: docker
      tags:
        - docker
        - tools

    - role: programming
      tags: programming

    - role: xfce
      tags: xfce
      when: is_xfce_installed

    - role: desktop
      tags: desktop
