---
- hosts: all
  gather_facts: yes
  pre_tasks:
    - name: Limit to Debian like distributions
      fail:
        msg: "{{ ansible_distribution }} is not supported with this tag."
      when: (ansible_distribution != "Ubuntu") and
            (ansible_distribution != "Debian")

- name: "Install basic_networking"
  gather_facts: false
  hosts: basic_networking
  roles:
    - role: curl
      tags:
        - basic_networking
        - curl
    - role: git
      tags:
        - basic_networking
        - git

- name: "Install shell"
  gather_facts: true
  hosts: shell
  roles:
    - role: common_shell
      tags:
        - shell
        - common_shell
    - role: zsh
      tags:
        - shell
        - zsh
    - role: tmux
      tags:
        - shell
        - tmux

- name: "Install common tools"
  hosts: common_tools
  roles:
    - role: minimal_shell
      tags:
        - common_tools
        - minimal_shell
