---
- hosts: all
  gather_facts: yes
  pre_tasks:
    - name: Limit to Debian like distributions
      fail:
        msg: "{{ ansible_distribution }} is not supported with this tag."
      when: (ansible_distribution != "Ubuntu") and
            (ansible_distribution != "Debian")

- name: "Install tools"
  gather_facts: false
  hosts: tools
  roles:
    - role: tools
      tags:
        - tools

- name: "Install shell"
  gather_facts: true
  hosts: shell
  roles:
    - role: shell
      tags:
        - shell
