---
- name: "Install Alacritty"
  apt:
    name: "alacritty={{ alacritty_version }}"
    state: present
  become: true

- name: "Install xdotool + xsel"
  apt:
    name:
      - xdotool
      - xsel
    state: present
  become: true

- name: Add dependencies for launch script
  ansible.builtin.apt:
    name:
      - wmctrl
    state: present
  become: true

- name: "Copy launch alacritty script"
  copy:
    src: launch-alacritty-in-ws.sh
    dest: /usr/local/bin/
    mode: 'u=rwx,go=rx'
  become: true

- name: "Edit alacritty configuration"
  ansible.builtin.template:
    src: alacritty/alacritty.yml.j2
    dest: ~/.config/alacritty/alacritty.yml
    mode: 'u=rwx,g=rx'
  vars:
    font_name: "{{ shell_fonts[shell_font]['name'] }}"
