---
- name: "Install MS Core fonts"
  apt:
    name:
      - ttf-mscorefonts-installer
      - fonts-crosextra-carlito
      - fonts-crosextra-caladea
    state: present
  become: true

- name: "Install Google fonts"
  copy:
    src: "{{ item }}"
    dest: /usr/share/fonts/
    mode: 'u=rw,go=r'
  become: true
  loop: "{{ query('fileglob', 'files/fonts/*.ttf') }}"
