---
- name: "Limit to Ubuntu distributions"
  import_role:
    name: utils
    tasks_from: filter_distribution

- name: "Install desktop fonts"
  import_tasks: desktop_fonts.yml
  tags: desktop_fonts

- name: "Install Urxvt"
  import_tasks: urxvt.yml
  tags: urxvt

- name: "Install Firefox"
  import_tasks: firefox.yml
  tags: firefox

- name: "Install VLC"
  import_tasks: vlc.yml
  tags: vlc

- name: "Install VSCode"
  import_tasks: vscode.yml
  tags: vscode
