---
- name: "Install desktop fonts"
  import_tasks: desktop_fonts.yml
  tags: desktop_fonts

- name: "Install shell fonts"
  import_tasks: shell_fonts.yml
  tags: shell_fonts

- name: "Install alacritty"
  import_tasks: alacritty.yml
  tags: alacritty

- name: "Install mupdf"
  import_tasks: mupdf.yml
  tags: pdf

- name: "Install Firefox"
  import_tasks: firefox.yml
  tags: firefox

- name: "Install VSCode"
  import_tasks: vscode.yml
  tags: vscode

- name: "Install Veracrypt"
  import_tasks: veracrypt.yml
  tags: veracrypt

- name: "Install VLC"
  import_tasks: vlc.yml
  tags: vlc
