---
- name: "Check if font sources are downloaded for {{ font_name }}"
  ansible.builtin.stat:
    path: "/tmp/shell_fonts/{{ font_url | basename }}"
  register: desktop_font_archive_stated
  changed_when: false

- name: "Get fonts for {{ font_name }}"
  ansible.builtin.get_url:
    url: "{{ font_url }}"
    dest: "/tmp/shell_fonts/{{ font_url | basename }}"
    mode: "u=rwx,go=rx"
  become: true
  when: not desktop_font_archive_stated.stat.exists or desktop_force_shell_font
  register: desktop_get_shell_font

- name: "Deploy font for {{ font_name }}"
  ansible.builtin.unarchive:
    src: "/tmp/shell_fonts/{{ font_url | basename }}"
    dest: /usr/share/fonts
    mode: "u=rwx,go=rx"
  become: true
  when: desktop_get_shell_font.changed or desktop_force_shell_font
