---
- name: Install fontconfig
  apt:
    name: fontconfig
    state: present
  become: true

- name: Install nerd shell fonts
  ansible.builtin.unarchive:
    src: "{{ item.value.url }}"
    dest: /usr/share/fonts
    remote_src: true
    mode: "u=rwx,go=rx"
  loop: "{{  shell_fonts | dict2items }}"
  become: true
  notify:
    - Refresh font cache
