---
- name: Install fontconfig
  apt:
    name: fontconfig
    state: present
  become: true

- name: Create tmp folder for font
  ansible.builtin.file:
    mode: "u=rwx,go=rx"
    path: "/tmp/shell_fonts"
    state: directory
  become: true

- name: "Install nerd fonts"
  vars:
    font_name: "{{ item.key }}"
    font_url: "{{ item.value.url }}"
  include_tasks:
    file: shell_font_dl.yml
    apply:
      tags: "shell_fonts"
  loop: "{{  shell_fonts | dict2items }}"
