---
- name: "Install Urxvt"
  apt:
    name: rxvt-unicode
    state: present
  become: true

- name: "Install xdotool + xsel"
  apt:
    name:
      - xdotool
      - xsel
    state: present
  become: true

- name: "Copy launch Urxvt script"
  copy:
    src: launch-in-workspace.sh
    dest: /usr/local/bin/
    mode: 'u=rwx,go=rx'
  become: true

- name: "Edit .Xresources"
  copy:
    src: Xresources
    dest: ~/.Xresources
    mode: 'u=rwx,g=rx'
