---
- name: "Install Urxvt"
  apt:
    name: rxvt-unicode
    state: present
  become: yes

- name: "Install xdotool + xsel"
  apt:
    name:
      - xdotool
      - xsel
    state: present
  become: yes

- name: "Check urxvt config directory exists"
  file:
    path: ~/.urxvt
    state: directory
    mode: 'u=rwx,g=rx'

- name: "Copy launch Urxvt script"
  copy:
    src: launch-in-workspace.sh
    dest: ~/.urxvt/
    mode: 'u=rwx,g=rx'

- name: "Edit .Xresources"
  copy:
    src: Xresources
    dest: ~/.Xresources
    mode: 'u=rwx,g=rx'
