---
- name: Install Veracrypt
  ansible.builtin.apt:
    deb: "https://launchpad.net/veracrypt/trunk/{{ desktop_veracrypt_version }}/+download/{{ desktop_veracrypt_artifact_version }}.deb"
    state: present
  become: true
