---
- name: "Install GPG"
  apt:
    name: gpg
    state: present
  become: true

- name: "Download ASC file"
  apt_key:
    url: "{{ vscode_microsoft_asc_url }}"
    state: present
  become: true

- name: "Copy repo list"
  copy:
    src: vscode.list
    dest: /etc/apt/sources.list.d/vscode.list
    mode: 'u=rw,go=r'
  become: true

- name: "Install Visual Studio Code"
  apt:
    name: code
    state: present
    update_cache: true
  become: true

- name: "Export installed VSCode extensions"
  command: code --list-extensions
  register: vscode_installed_extensions
  changed_when: false

- name: "Install missing VSCode extensions"
  vars:
    missing_extensions: "{{ vscode_extensions | difference(vscode_installed_extensions.stdout_lines) }}"
  command: code --install-extension {{ item }}
  loop: "{{ missing_extensions }}"
  when: missing_extensions | length > 0

- name: "Add alias to launch VSCode easily"
  blockinfile:
    path: ~/.zshrc_post
    marker: "# {mark} ANSIBLE MANAGED vscode BLOCK -->"
    block: |
      alias xc="code --new-window ."
    create: true
    mode: 'u=rw,g=r'
