---
- name: Install numix theme and icons
  ansible.builtin.apt:
    name:
      - numix-gtk-theme
      - numix-icon-theme
    state: present
  become: true

- name: Copy XFCE xfconf settings
  ansible.builtin.copy:
    src: xfconf/
    dest: ~/.config/xfce4/xfconf/xfce-perchannel-xml/
    mode: 'u=rw,go=r'
  tags: xfce_conf
  register: xfce_xconf_settings
  notify:
    - Recommend X refresh

- name: Install move-to-next-monitor dependencies
  ansible.builtin.apt:
    name:
      - x11-utils
      - wmctrl
      - xdotool
    state: present
  become: true
  tags: xfce_move_window_to_monitor

- name: Install move-to-next-monitor
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/jc00ke/move-to-next-monitor/master/move-to-next-monitor
    dest: /usr/local/bin/move-to-next-monitor
    mode: 'u=rwx,go=rx'
  become: true
  tags: xfce_move_window_to_monitor

- name: Install Rofi
  import_tasks: rofi.yml
  tags: rofi

- name: Configure panel
  ansible.builtin.command: "xfce4-panel-profiles load {{ role_path }}/files/panel/{{ xfce_panel_profile }}.tar.bz2"
  tags: xfce_panel
  when: xfce_xconf_settings is defined and xfce_xconf_settings.changed or xfce_force_panel_refresh

- name: Configure lightdm
  ansible.builtin.copy:
    src: lightdm/
    dest: /etc/lightdm
    mode: 'u=rw,go=r'
  become: true
  tags: lightdm
