---
- name: Install orchis theme and numix icons
  ansible.builtin.apt:
    name:
      - orchis-gtk-theme
      - numix-icon-theme
    state: present
  become: true

- name: Copy XFCE xfconf settings
  ansible.builtin.copy:
    src: xfconf/
    dest: ~/.config/xfce4/xfconf/xfce-perchannel-xml/
    mode: 'u=rw,go=r'
  tags: xfce_conf
  register: xfce_xconf_settings
  notify:
    - Recommend X refresh

- name: Install move-to-next-monitor dependencies
  ansible.builtin.apt:
    name:
      - x11-utils
      - wmctrl
      - xdotool
    state: present
  become: true
  tags: xfce_move_window_to_monitor

- name: Install move-to-next-monitor
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/jc00ke/move-to-next-monitor/master/move-to-next-monitor
    dest: /usr/local/bin/move-to-next-monitor
    mode: 'u=rwx,go=rx'
  become: true
  tags: xfce_move_window_to_monitor

- name: Install Rofi
  import_tasks: rofi.yml
  tags: rofi
