---
- name: Install Rofi
  ansible.builtin.apt:
    name: rofi
    state: present
  become: true

- name: Init Rofi configuration
  ansible.builtin.file:
    path: ~/.config/rofi
    state: directory
    mode: 'u=rwx,go=rx'

- name: Copy Rofi settings
  ansible.builtin.copy:
    src: rofi/
    dest: ~/.config/rofi/
    mode: 'u=rw,go=r'
