---
- name: "Install MS Core fonts"
  apt:
    name:
      - ttf-mscorefonts-installer
      - fonts-crosextra-carlito
      - fonts-crosextra-caladea
    state: present
  become: yes

- name: "Install Google fonts"
  get_url:
    url: "{{ item }}"
    dest: /usr/share/fonts/
  become: yes
  loop: "{{ google_fonts }}"
