---
git_username: null
git_email: null
# Keep a null key if you don't gpg sign
git_signing_key: null

shell_user_locales:
  LANG: en_US.UTF-8
  LANGUAGE: en
  LC_ADDRESS: en_US.UTF-8
  LC_COLLATE: C
  LC_CTYPE: en_US.UTF-8
  LC_MONETARY: en_US.UTF-8
  LC_MEASUREMENT: en_US.UTF-8
  LC_MESSAGES: en_US.UTF-8
  LC_NAME: en_US.UTF-8
  LC_NUMERIC: en_US.UTF-8
  LC_PAPER: en_US.UTF-8
  LC_RESPONSE: en_US.UTF-8
  LC_TELEPHONE: en_US.UTF-8
  LC_TIME: en_US.UTF-8

shell_extra_locales: []

oh_my_zsh_plugins:
  - git
  - zsh-autosuggestions

oh_my_sh_extra_plugins:
  zsh-autosuggestions: https://github.com/zsh-users/zsh-autosuggestions
