---
- name: "Apply dconf keybinding for template"
  block:
    - name: "Extract {{ gnome_keys_path }} currently applied"
      shell: >
        dconf dump {{ gnome_keys_path }} > /tmp/org_{{ keybinding_template }}
      changed_when: false

    - name: "Calculate current {{ gnome_keys_path }} checksum"
      stat:
        path: "/tmp/org_{{ keybinding_template }}"
      register: original_keybinding

    - name: Apply {{ gnome_keys_path }} template temporarily
      template:
        src: '{{ keybinding_template }}.j2'
        dest: '/tmp/new_{{ keybinding_template }}'
        mode: 'u=rw,g=r'
      changed_when: false

    - name: "Calculate new {{ gnome_keys_path }} checksum"
      stat:
        path: "/tmp/new_{{ keybinding_template }}"
      register: new_keybinding

    - name: "Apply keybinding {{ gnome_keys_path }} to host"
      shell: >
        dconf load {{ gnome_keys_path }} < /tmp/new_{{ keybinding_template }}
      when: original_keybinding.stat.checksum != new_keybinding.stat.checksum
  vars:
    gnome_keys_path: '/{{ keybinding_template | replace(".", "/") }}/'
