---
- name: "Install dconf"
  apt:
    name:
      - dconf-cli
      - dconf-editor
    state: present
  become: yes

- name: "Load gnome wm keybindings into gnome"
  vars:
    keybinding_file: 'org.gnome.desktop.wm.keybindings'
  include_tasks: dconf_keybinding_from_file.yml

- name: "Load gnome shell keybindings into gnome"
  vars:
    keybinding_file: 'org.gnome.shell.keybindings'
  include_tasks: dconf_keybinding_from_file.yml

- name: "Load gnome media-keys into gnome"
  vars:
    keybinding_template: 'org.gnome.settings-daemon.plugins.media-keys'
  include_tasks: dconf_keybinding_from_template.yml

- name: "Install gnome tweaks"
  apt:
    name: gnome-tweaks
    state: present
  become: yes
