---
- name: "Install gnome tweaks"
  apt:
    name: gnome-tweaks
    state: present
  become: true

- name: "Install numix theme and icons"
  apt:
    name:
      - numix-gtk-theme
      - numix-icon-theme
    state: present
  become: true

- name: "Install chrome-gnome-shell"
  apt:
    name: chrome-gnome-shell
    state: present
  become: true
