---
- name: "Install plugin {{ plugin_name }} prerequisites"
  apt:
    name: "{{ plugin_apt_prerequisites }}"
    state: present
  when: plugin_apt_prerequisites
  become: true

- name: "Add plugin {{ plugin_name }}"
  # asdf return error 2 if plugin is already there
  shell: "asdf plugin-add {{ plugin_name }} {{ plugin_url }} || /bin/true"
  register: added_plugin
  changed_when: '"already added" not in added_plugin.stderr'

- name: "Get installed versions of {{ plugin_name }}"
  ansible.builtin.command: "asdf list {{ plugin_name }}"
  register: raw_installed_version
  changed_when: false

- name: "Format installed versions of {{ plugin_name }}"
  ansible.builtin.set_fact:
    installed_version: "{{ raw_installed_version.stdout_lines | map('trim') }}"

# Quick fix to solve old release GPG check issues
- name: "Install GPG for nodejs"
  ansible.builtin.shell:
    cmd: ~/.asdf/plugins/nodejs/bin/import-previous-release-team-keyring
  when: plugin_name == "nodejs" and not raw_installed_version.stdout_lines

- name: "Install versions for {{ plugin_name }}"
  ansible.builtin.command: "asdf install {{ plugin_name }} {{ plugin_version }}"
  when: plugin_version not in installed_version
  loop: "{{ plugin_versions }}"
  loop_control:
    loop_var: plugin_version

- name: "Register default plugin version for {{ plugin_name }}"
  blockinfile:
    path: ~/.tool-versions
    marker: "# {mark} ANSIBLE MANAGED {{ plugin_name }} BLOCK -->"
    block: |
      {{ plugin_name }} {{ plugin_versions[0] }}
    create: true
    mode: 'u=rw,g=r'
  when: plugin_versions
