---
- name: Install cheat.sh requirements
  ansible.builtin.apt:
    name: rlwrap
    state: present
  become: true

- name: Install cheat.sh
  ansible.builtin.get_url:
    url: https://cht.sh/:cht.sh
    dest: /usr/local/bin/cht.sh
    mode: "u=rwx,go=rx"
  become: true
