---
- name: Install gvm dependencies
  apt:
    name:
      - mercurial
      - make
      - binutils
      - bison
      - gcc
      - build-essential
    state: present
  become: yes

- name: Check gvm installation
  stat:
    path: ~/.gvm
  register: gvm_installed

- name: Fetch gvm install script
  get_url:
    url: https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer
    dest: /tmp/gvm-installer
    mode: 'u=rwx,g=rx'
  when: not gvm_installed.stat.exists

- name: Launch gvm installer
  shell: bash /tmp/gvm-installer
  when: not gvm_installed.stat.exists

- name: Add gvm source in ~/.zshrc_post
  blockinfile:
    path: ~/.zshrc_post
    marker: "# {mark} ANSIBLE MANAGED GVM BLOCK -->"
    block: |
      source /home/kheraud/\.gvm/scripts/gvm
    create: true
    mode: 'u=rw,g=r'