---
- name: Install gcc / g++ / make
  ansible.builtin.import_tasks: build_essential.yml
  tags: build_essential

- name: Install cheat.sh
  ansible.builtin.import_tasks: cheat_sh.yml
  tags: cheat_sh

- name: Install tldr
  ansible.builtin.import_tasks: tldr.yml
  tags: tldr

- name: Check asdf command exists
  ansible.builtin.stat:
    path: /usr/local/bin/asdf
  register: programming_asdf_bin_path

- name: Fail if asdf is not available
  ansible.builtin.fail:
    msg: "Can't find asdf binary, you probably need to restart your terminal / session"
  when: not programming_asdf_bin_path.stat.exists

- name: Install asdf plugins
  vars:
    plugin_name: "{{ item.key }}"
    plugin_versions: "{{ item.value.versions | default([]) }}"
    plugin_apt_prerequisites: "{{ item.value.apt_prerequisites | default([]) }}"
    plugin_extra_zsh_pre_conf: "{{ item.value.extra_zsh_pre_conf | default('') }}"
    plugin_extra_zsh_post_conf: "{{ item.value.extra_zsh_post_conf | default('') }}"
  ansible.builtin.include_tasks:
    file: asdf_plugin.yml
    apply:
      tags: asdf_plugins
  tags: asdf_plugins
  loop: "{{ programming_asdf_plugins | dict2items }}"
