---
- name: "Install gcc / g++ / make"
  import_tasks: build_essential.yml
  tags: build_essential

- name: "Install cheat.sh"
  import_tasks: cheat_sh.yml
  tags: cheat_sh

- name: "Install tldr"
  import_tasks: tldr.yml
  tags: tldr

- name: Check asdf command exists
  stat:
    path: /usr/local/bin/asdf
  register: asdf_bin_path

- name: Fail if asdf is not available
  fail:
    msg: "Can't find asdf binary, you probably need to restart your terminal / session"
  when: not asdf_bin_path.stat.exists

# - name: Get asdf plugins/versions really installed
#   ansible.builtin.command: "asdf list"
#   register: raw_asdf_list
#   changed_when: false
#   tags: asdf_plugins

# - name: Format asdf plugins/versions
#   ansible.builtin.set_fact:
#     current_asdf_list: "{{ raw_asdf_list.stdout |
#               regex_replace('\\n[\\s*]{2}', '\\n- ') |
#               regex_replace('(^|\n)([^-].+)\\n', '\\1\\2:\\n') |
#               from_yaml }}"
#   tags: asdf_plugins

- name: "Install asdf plugins"
  vars:
    plugin_name: "{{ item.key }}"
    plugin_versions: "{{ item.value.versions | default([]) }}"
    plugin_apt_prerequisites: "{{item.value.apt_prerequisites | default([]) }}"
    plugin_extra_zsh_pre_conf: "{{item.value.extra_zsh_pre_conf }}"
    plugin_extra_zsh_post_conf: "{{item.value.extra_zsh_post_conf }}"
    versions_already_installed: "{{current_asdf_list[item.key] |default(None)}}" 
  include_tasks:
    file: asdf_plugin.yml
    apply:
      tags: "asdf_plugins"
  tags: "asdf_plugins"
  loop: "{{ asdf_plugins | dict2items }}"
