---
- name: "Install gcc / g++ / make"
  import_tasks: build_essential.yml
  tags: build_essential

- name: "Install cheat.sh"
  import_tasks: cheat_sh.yml
  tags: cheat_sh

- name: "Install tldr"
  import_tasks: tldr.yml
  tags: tldr

- name: Check asdf command exists
  stat:
    path: ~/.asdf/bin/asdf
  register: asdf_bin_path

- name: Fail if asdf is not available
  fail:
    msg: "Can't find asdf binary, you probably need to restart your terminal / session"
  when: not asdf_bin_path.stat.exists

- name: "Install asdf plugins"
  vars:
    plugin_name: "{{ item.key }}"
    plugin_url: "{{ item.value.url }}"
    plugin_versions: "{{ item.value.versions | default([]) }}"
    plugin_apt_prerequisites: "{{item.value.apt_prerequisites | default([]) }}"
  include_tasks:
    file: asdf_plugin.yml
    apply:
      tags: "asdf_plugins"
  tags: "asdf_plugins"
  loop: "{{ asdf_plugin_list |
          dict2items |
          selectattr(
            'key',
            'in',
            asdf_plugins | dict2items | map(attribute='key')
          ) |
          items2dict |
          combine(asdf_plugins, recursive=True, list_merge='keep') |
          dict2items }}"
