---
- name: Install tldr
  ansible.builtin.pip:
    name: "tldr=={{ tldr_version }}"
    # Here to force the usage of user pip
    # instead of ansible virtualenv location
    executable: "/home/kheraud/.asdf/shims/pip3"
