---
- name: "Limit to Ubuntu >= 24.04 distributions"
  ansible.builtin.fail:
    msg: "{{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }} is not supported by this playbook"
  when: (ansible_facts['distribution'] != "Ubuntu") or
        (ansible_facts['distribution_version'] is version("24.04", "<"))
