---
- name: Install network dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
    state: present
  become: true

- name: Install Ansible dependencies
  apt:
    name:
      - sudo
      - python3
      - python3-apt
      - python3-pip
      - python3-virtualenv
      - python3-setuptools
      - python3-psutil
    state: present
  become: true
