---
- name: Check if XFCE is installed
  ansible.builtin.stat:
    path: /usr/bin/xfce4-session
  register: utils_xfce_shell_path

- name: Register desktop environments
  ansible.builtin.set_fact:
    utils_is_xfce_installed: "{{ utils_xfce_shell_path.stat.exists }}"
