---
- name: Check if XFCE is installed
  stat:
    path: /usr/bin/xfce4-session
  register: xfce_shell_path

- name: Register desktop environments
  ansible.builtin.set_fact:
    is_xfce_installed: "{{ xfce_shell_path.stat.exists }}"
