---
- name: Install Git
  apt:
    name: git
    state: present
  become: yes

- name: Copy gitignore configuration
  copy:
    src: gitignore
    dest: ~/.gitignore

- name: Apply gitconfig configuration
  template:
    src: gitconfig
    dest: ~/.gitconfig

- name: Add git-extra
  apt:
    name: git-extras
    state: present
  become: yes