---
tldr_version: "3.2.0"

asdf_plugin_list:
  python:
    url: https://github.com/danhper/asdf-python.git
    apt_prerequisites:
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - libncurses5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev
  nodejs:
    url: https://github.com/asdf-vm/asdf-nodejs.git
    apt_prerequisites:
      - dirmngr
      - gpg
      - curl
      - gawk
  golang:
    url: https://github.com/kennyp/asdf-golang.git
    apt_prerequisites:
      - coreutils
      - curl
  yarn:
    url: https://github.com/twuni/asdf-yarn.git
  java:
    url: https://github.com/halcyon/asdf-java.git
    apt_prerequisites:
      - bash
      - coreutils
      - curl
      - unzip
      - jq
