---
tldr_version: "2.0.0"

asdf_plugin_list:
  python:
    url: https://github.com/danhper/asdf-python.git
    apt_prerequisites:
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - libncurses5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev
  poetry:
    url: https://github.com/asdf-community/asdf-poetry.git
  nodejs:
    url: https://github.com/asdf-vm/asdf-nodejs.git
    apt_prerequisites:
      - dirmngr
      - gpg
      - curl
      - gawk
  golang:
    url: https://github.com/kennyp/asdf-golang.git
    apt_prerequisites:
      - coreutils
      - curl
  yarn:
    url: https://github.com/twuni/asdf-yarn.git
  java:
    url: https://github.com/halcyon/asdf-java.git
    apt_prerequisites:
      - bash
      - coreutils
      - curl
      - unzip
      - jq
  scala:
    url: https://github.com/mtatheonly/asdf-scala.git
  github-cli:
    url: https://github.com/bartlomiejdanek/asdf-github-cli.git
  kubectl:
    url: https://github.com/Banno/asdf-kubectl.git
  kubectx:
    url: https://gitlab.com/wt0f/asdf-kubectx.git
  minikube:
    url: https://github.com/alvarobp/asdf-minikube.git
  kind:
    url: https://github.com/johnlayton/asdf-kind.git
  helm:
    url: https://github.com/Antiarchitect/asdf-helm.git
  terraform:
    url: https://github.com/Banno/asdf-hashicorp.git
  vault:
    url: https://github.com/Banno/asdf-hashicorp.git
  packer:
    url: https://github.com/Banno/asdf-hashicorp.git
  awscli:
    url: https://github.com/MetricMike/asdf-awscli.git
  gcloud:
    url: https://github.com/jthegedus/asdf-gcloud.git
