---
- name: "Install xz-utils required for remote deb install"
  apt:
    name: xz-utils
    state: present
  become: yes

- name: "Install Slack"
  apt:
    deb: "https://downloads.slack-edge.com/linux_releases/slack-desktop-{{ slack_version }}-amd64.deb"
    state: present
  become: yes
