---
- name: Install asdf
  ansible.builtin.unarchive:
    src: https://github.com/asdf-vm/asdf/releases/download/v{{asdf_version}}/asdf-v{{asdf_version}}-linux-amd64.tar.gz
    dest: /usr/local/bin
    mode: "u=rwx,go=rx"
    remote_src: true
  become: true

- name: Add asdf preload
  blockinfile:
    path: ~/.zshrc_post
    create: true
    marker: "# {mark} ANSIBLE MANAGED ASDF BLOCK -->"
    block: |
      export ASDF_DATA_DIR="$HOME/.asdf"
      export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"
    mode: 'u=rw,g=r'
