---
- name: Install htop
  apt:
    name: htop
    state: present
  become: true

- name: Check htop config directory exists
  file:
    path: ~/.config/htop
    state: directory
    mode: 'u=rwx,g=rx'

- name: Copy Htop configuration
  copy:
    src: htop/htoprc
    dest: ~/.config/htop/htoprc
    mode: 'u=rw,g=r'
