---
- name: Install httpie
  ansible.builtin.pip:
    name: "httpie=={{ httpie_version }}"
    # Here to force the usage of sysem pip
    # instead of virtualenv location
    executable: "/usr/bin/pip3"
