---
- name: Unarchive ngrok binary
  ansible.builtin.unarchive:
    src: "https://bin.equinox.io/c/{{ tools_ngrok_version }}/ngrok-stable-linux-amd64.zip"
    dest: /usr/local/bin
    remote_src: true
  become: true
