---
- name: Fetch todo.txt cli
  ansible.builtin.unarchive:
    src: "https://github.com/todotxt/todo.txt-cli/releases/download/v{{ todo_txt_version }}/todo.txt_cli-{{ todo_txt_version }}.tar.gz"
    dest: /tmp
    remote_src: true
    creates: /usr/local/bin/todo.sh
  become: true

- name: Add todo.txt cli
  ansible.builtin.copy:
    src: "/tmp/todo.txt_cli-{{ todo_txt_version }}/"
    dest: /usr/local/bin
    remote_src: true
  become: true

- name: Init todo.txt cli configuration
  ansible.builtin.file:
    path: ~/.config/todo
    state: directory
    mode: 'u=rwx,go=rx'

- name: Copy todo.txt cli settings
  ansible.builtin.template:
    src: todo/todo_config.j2
    dest: ~/.config/todo/config
    mode: 'u=rw,go=r'

- name: Install rofi
  import_role:
    name: xfce
    tasks_from: rofi

- name: Add todofi script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hugokernel/todofi.sh/master/todofi.sh
    dest: /usr/local/bin/
    mode: 'u=rwx,go=rx'
  become: true

- name: Copy todofi settings
  ansible.builtin.copy:
    src: todo/todofish.conf
    dest: ~/.config/todofish.conf
    mode: 'u=rw,go=r'
