---
- name: Install Topydo
  pip:
    name:
      - topydo
      - topydo[columns]
      - topydo[prompt]

- name: Add aliases to todos
  blockinfile:
    path: ~/.zshrc_post
    marker: "# {mark} ANSIBLE MANAGED TOPYDO BLOCK -->"
    block: |
      {% for todo_elt in todo_context %}
      alias {{ todo_elt.alias }}="topydo \
      -c {{ todo_path }}/{{ todo_elt.name }}-topydo.conf \
      -d {{ todo_path }}/{{ todo_elt.name }}-done.txt \
      -t {{ todo_path }}/{{ todo_elt.name }}.txt columns \
      -l {{ todo_path }}/{{ todo_elt.name }}-topydo_columns.conf"
      alias {{ todo_elt.alias }}-cli="topydo \
      -c {{ todo_path }}/{{ todo_elt.name }}-topydo.conf \
      -d {{ todo_path }}/{{ todo_elt.name }}-done.txt \
      -t {{ todo_path }}/{{ todo_elt.name }}.txt"
      {% endfor %}
    create: true
    mode: 'u=rw,g=r'

- name: Fetch todo.txt cli
  unarchive:
    src: https://github.com/todotxt/todo.txt-cli/releases/download/v{{ todo_txt_version }}/todo.txt_cli-{{ todo_txt_version }}.tar.gz
    dest: /tmp
    remote_src: true
  become: true

- name: Add todo.txt cli
  ansible.builtin.copy:
    src: "/tmp/todo.txt_cli-{{  todo_txt_version  }}/"
    dest: /usr/local/bin
    remote_src: yes
  become: true
