---
- name: Install fd package
  apt:
    name: fd-find
    state: present
  become: yes

- name: Get fdfind path
  shell: which fdfind
  register: fdfind_path
  changed_when: false
  ignore_errors: true

- name: Add alias for fdfind
  lineinfile:
    path: '~/.zshrc_local'
    regexp: '^alias fd='
    line: 'alias fd="{{ fdfind_path.stdout }}"'
  when: fdfind_path is succeeded
