---
- import_tasks: fzf.yml
  tags:
    - minimal_shell
    - fzf

- import_tasks: bat.yml
  tags:
    - minimal_shell
    - bat

- import_tasks: exa.yml
  tags:
    - minimal_shell
    - exa

- import_tasks: fd.yml
  tags:
    - minimal_shell
    - fd

- import_tasks: ripgrep.yml
  tags:
    - minimal_shell
    - ripgrep
