---
- name: "Ensure previous versions are not installed"
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - docker-compose
      - docker-compose-v2
      - docker-doc
      - podman-docker
    state: absent
  become: true

- name: "Ensure dependencies are installed"
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
  become: true

- name: "Download keyring file"
  get_url:
    url: "{{ docker_apt_key_url }}"
    dest: /etc/apt/keyrings/docker.asc
    mode: "a+r"
  become: true

- name: "Copy repo list"
  template:
    src: docker.list.j2
    dest: /etc/apt/sources.list.d/docker.list
    mode: 'u=rw,go=r'
  become: true

- name: "Install docker"
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true
  become: true
