---
- name: "Ensure previous versions are not installed"
  apt:
    name:
      - docker
      - docker-engine
    state: absent
  become: true

- name: "Ensure dependencies are installed"
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
  become: true

- name: "Download ASC file"
  apt_key:
    url: "{{ docker_apt_key_url }}"
    state: present
  become: true

- name: "Copy repo list"
  template:
    src: docker.list.j2
    dest: /etc/apt/sources.list.d/docker.list
    mode: 'u=rw,go=r'
  become: true

- name: "Update software cache for apt-get"
  apt:
    update_cache: yes
  become: true
  changed_when: false

- name: "Install docker"
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  become: true