---

# Shell configs
git_username: null
git_email: null
# Keep a null key if you don't gpg sign
git_signing_key: null

# Define which language is expected for each console need
shell_user_locales:
  LANG: en_US.UTF-8
  LANGUAGE: en
  LC_ADDRESS: en_US.UTF-8
  LC_COLLATE: C
  LC_CTYPE: en_US.UTF-8
  LC_MONETARY: en_US.UTF-8
  LC_MEASUREMENT: en_US.UTF-8
  LC_MESSAGES: en_US.UTF-8
  LC_NAME: en_US.UTF-8
  LC_NUMERIC: en_US.UTF-8
  LC_PAPER: en_US.UTF-8
  LC_RESPONSE: en_US.UTF-8
  LC_TELEPHONE: en_US.UTF-8
  LC_TIME: en_US.UTF-8

# If you want extra languages to be installed, list them here
shell_extra_locales: []

# List here the omz plugins you want to enable
oh_my_zsh_plugins:
  - git
  - zsh-autosuggestions
  - fzf
  - zsh-eza
  - tmux
  - autojump
  - asdf
  - direnv
  # - kubectl
  # - helm // Slow loading

# List here remote omz plugins you want to install
oh_my_sh_extra_plugins:
  zsh-autosuggestions: https://github.com/zsh-users/zsh-autosuggestions

# Programming configs
# List of asdf plugins to install with the list of versions expected for
# each plugin
asdf_plugins:
  python:
    apt_prerequisites:
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - libncurses5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev
    versions:
      - "latest"
      - "3.12.5"
      - "3.11.9"
      - "3.11.8"
  nodejs:
    apt_prerequisites:
      - dirmngr
      - gpg
      - curl
      - gawk
    versions:
      - "latest"
      - "19.9.0"
      - "20.11.1"
      - "21.7.3"
  golang:
    apt_prerequisites:
      - coreutils
      - curl
    versions:
      - "latest"
      - "1.17"
  github-cli:
    versions:
      - "latest"
  glab:
    versions:
      - "latest"
  kubectl:
    versions:
      - "latest"
    extra_zsh_post_conf: |
      source <(kubectl completion zsh)
  kubecolor:
    versions:
      - "latest"
    extra_zsh_post_conf: |
      alias kubectl=kubecolor
      alias k=kubecolor
      compdef kubecolor=kubectl
  kubie:
    versions:
      - "latest"
    extra_zsh_post_conf: |
      alias kctx="kubie ctx"
      alias kns="kubie ns"
  krew:
    versions:
      - "latest"
  clusterctl:
    versions:
      - "latest"
  kind:
    versions:
      - "latest"
  helm:
    versions:
      - "latest"
  terraform:
    versions:
      - "latest"
  vault:
    versions:
      - "latest"
  packer:
    versions:
      - "latest"
  awscli:
    versions:
      - "latest"

# Desktop configs
# List of VS Code extension to install
vscode_extensions:
  - 4ops.terraform
  - arjun.swagger-viewer
  - davidanson.vscode-markdownlint
  - dbaeumer.vscode-eslint
  - donjayamanne.githistory
  - eamodio.gitlens
  - editorconfig.editorconfig
  - esbenp.prettier-vscode
  - fabiospampinato.vscode-diff
  - golang.go
  - hilleer.yaml-plus-json
  - jebbs.plantuml
  - mhutchie.git-graph
  - ms-azuretools.vscode-docker
  - ms-kubernetes-tools.vscode-kubernetes-tools
  - ms-python.python
  - ms-toolsai.jupyter
  - ms-vscode-remote.remote-containers
  - ms-vsliveshare.vsliveshare
  - redhat.vscode-yaml
  - techer.open-in-browser
  - vscode-icons-team.vscode-icons
  - vscode-snippet.snippet
  - xabikos.javascriptsnippets
  - yzane.markdown-pdf
  - yzhang.markdown-all-in-one

# Font in terminal
# valid options: roboto, iosevka, hack, firacode, dejavu
shell_font: "hack"
