---

# Shell configs
git_username: null
git_email: null
# Keep a null key if you don't gpg sign
git_signing_key: null

# Define which language is expected for each console need
shell_user_locales:
  LANG: en_US.UTF-8
  LANGUAGE: en
  LC_ADDRESS: en_US.UTF-8
  LC_COLLATE: C
  LC_CTYPE: en_US.UTF-8
  LC_MONETARY: en_US.UTF-8
  LC_MEASUREMENT: en_US.UTF-8
  LC_MESSAGES: en_US.UTF-8
  LC_NAME: en_US.UTF-8
  LC_NUMERIC: en_US.UTF-8
  LC_PAPER: en_US.UTF-8
  LC_RESPONSE: en_US.UTF-8
  LC_TELEPHONE: en_US.UTF-8
  LC_TIME: en_US.UTF-8

# If you want extra languages to be installed, list them here
shell_extra_locales: []

# List here the omz plugins you want to enable
oh_my_zsh_plugins:
  - git
  - zsh-autosuggestions
  - fzf
  - zsh-eza
  - tmux
  - autojump
  - asdf
  - kubectl
  # - helm // Slow loading

# List here remote omz plugins you want to install
oh_my_sh_extra_plugins:
  zsh-autosuggestions: https://github.com/zsh-users/zsh-autosuggestions

# Programming configs
# List of asdf plugins to install with the list of versions expected for
# each plugin
asdf_plugins:
  python:
    versions:
      - "3.10.3"
  nodejs:
    versions:
      - "19.9.0"
      - "20.11.1"
  golang:
    versions:
      - "1.17"
  yarn:
    versions:
      - "1.22.18"
  java:
    versions:
      - adoptopenjdk-12.0.2+10.1
  scala:
    versions:
      - "2.13.8"
  github-cli:
    versions:
      - "2.45.0"
  kubectl:
    versions:
      - "1.23.5"
  kubectx:
    versions:
      - "0.9.4"
  minikube:
    versions:
      - "1.25.2"
  kind:
    versions:
      - "0.12.0"
  helm:
    versions:
      - "3.8.1"
  terraform:
    versions:
      - "1.7.4"
  vault:
    versions:
      - "1.9.4"
  packer:
    versions:
      - "1.8.0"
  awscli:
    versions:
      - "2.15.28"


# Desktop configs
# List of VS Code extension to install
vscode_extensions:
  - 4ops.terraform
  - arjun.swagger-viewer
  - davidanson.vscode-markdownlint
  - dbaeumer.vscode-eslint
  - donjayamanne.githistory
  - eamodio.gitlens
  - editorconfig.editorconfig
  - esbenp.prettier-vscode
  - fabiospampinato.vscode-diff
  - golang.go
  - hilleer.yaml-plus-json
  - hookyqr.beautify
  - jebbs.plantuml
  - mhutchie.git-graph
  - ms-azuretools.vscode-docker
  - ms-kubernetes-tools.vscode-kubernetes-tools
  - ms-python.python
  - ms-toolsai.jupyter
  - ms-vscode-remote.remote-containers
  - ms-vsliveshare.vsliveshare
  - redhat.vscode-yaml
  - techer.open-in-browser
  - vscode-icons-team.vscode-icons
  - vscode-snippet.snippet
  - xabikos.javascriptsnippets
  - yzane.markdown-pdf
  - yzhang.markdown-all-in-one

# Font in terminal
# valid options: roboto, iosevka, hack, firacode, dejavu
shell_font: "hack"
