---
# This file list all the default config, override specific ones

# Extended_desktop configs
# Location of yarr database (use a synchronisation / replicated location)
yarr_db_path: "~/Sync/Applications/yarr/common-feeds.db"
# Port on which yarr is listening : http://localhost:<yarr_local_port>
yarr_local_port: 7070

# Programming configs
# List of asdf plugins to install with the list of versions expected for
# each plugin
asdf_plugins:
  python:
    versions:
      - "3.10.3"
  nodejs:
    versions:
      - "16.14.2"
  golang:
    versions:
      - "1.17"

# Shell configs
git_username: null
git_email: null
# Keep a null key if you don't gpg sign
git_signing_key: null

# Define which language is expected for each console need
shell_user_locales:
  LANG: en_US.UTF-8
  LANGUAGE: en
  LC_ADDRESS: en_US.UTF-8
  LC_COLLATE: C
  LC_CTYPE: en_US.UTF-8
  LC_MONETARY: en_US.UTF-8
  LC_MEASUREMENT: en_US.UTF-8
  LC_MESSAGES: en_US.UTF-8
  LC_NAME: en_US.UTF-8
  LC_NUMERIC: en_US.UTF-8
  LC_PAPER: en_US.UTF-8
  LC_RESPONSE: en_US.UTF-8
  LC_TELEPHONE: en_US.UTF-8
  LC_TIME: en_US.UTF-8

# If you want extra languages to be installed, list them here
shell_extra_locales: []

# List here the omz plugins you want to enable
oh_my_zsh_plugins:
  - git
  - zsh-autosuggestions

# List here remote omz plugins you want to install
oh_my_sh_extra_plugins:
  zsh-autosuggestions: https://github.com/zsh-users/zsh-autosuggestions

# Xfce configs
# If xfce configuration does not change, panel is not refreshed
# If you want to force panel refresh, use this var
xfce_force_panel_refresh: false
# If you want to define a different panel profile, define it here
# valid options: default, purple-haze
xfce_panel_profile: default

# Tools configs
# Location of todo.txt files (use a synchronisation / replicated location)
todo_path: /usr/local/bin

# Desktop configs
# List of VS Code extension to install
vscode_extensions: []
# Font in uRXVT terminal
# valid options: roboto, iosevka, hack, firacode
urxvt_font: "roboto"
