---
- name: Install htop
  apt:
    name: htop
    state: present
  become: yes

- name: Check htop config directory exists
  file:
    path: ~/.config/htop
    state: directory

- name: Copy Htop configuration
  copy:
    src: htoprc
    dest: ~/.config/htop/htoprc
