---
- name: "Launch Kubernetes installation"
  import_tasks: kubernetes.yml

- name: "Launch Helm installation"
  import_tasks: helm.yml

- name: "Launch Minikube installation"
  import_tasks: minikube.yml
