---
- name: "Install Virtualbox"
  apt:
    name: virtualbox
    state: present
  become: true

- name: "Install xz-utils required for remote deb install"
  apt:
    name: xz-utils
    state: present
  become: true

- name: "Install Minikube"
  apt:
    deb: "https://github.com/kubernetes/minikube/releases/download/v{{ minikube_version }}/minikube_{{ minikube_version }}-0_amd64.deb"
    state: present
  become: true
