---
- name: Install fd package
  apt:
    name: fd-find
    state: present
  become: yes

- name: Get fdfind path
  shell: which fdfind
  register: fdfind_path
  changed_when: false
  ignore_errors: true

- name: Add alias for fdfind
  blockinfile:
    path: ~/.zshrc_post
    marker: "# {mark} ANSIBLE MANAGED fd BLOCK -->"
    block: |
      alias fd="{{ fdfind_path.stdout }}"
    create: true
  when: fdfind_path is succeeded
