---
- name: Install bat package
  apt:
    name: bat
    state: present
  become: yes

- name: Stat for batcat bin
  stat:
    path: '/usr/bin/batcat'
  register: batcat_bin

- name: Add alias for batcat
  blockinfile:
    path: ~/.zshrc_local
    marker: "# {mark} ANSIBLE MANAGED BAT BLOCK -->"
    block: |
      alias bat="/usr/bin/batcat"
  when: batcat_bin.stat.exists == true

